package com.example.vix_schoters_dicksenalfersiusnovian.models


//Generated by JSONtoKotlin Plugin
data class NewsArticle(
    val articles: MutableList<Article>,
    val status: String,
    val totalResults: Int
)